version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: civic-weave-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: civic_weave
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c shared_preload_libraries=vector

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: civic-weave-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: civic_weave
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: civic-weave-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  batch-matching:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    container_name: civic-weave-batch-matching
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: civic_weave
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/var/log
    ports:
      - "5001:5000"

volumes:
  postgres_data:
